# This is a basic workflow to help you get started with Actions

name: Curl Jenkins Job Status

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  #push:
   # branches: [ "develop" ]
  #pull_request:
  #  branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8 #install the python needed
              - name: Install dependencies
            run: |
              python3 -m pip install --upgrade pip
      - name: Run python script to trigger build and fetch job number
        run: |
          # making file runnable (might be unnecessary)...
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/jenkins-trigger-build.py"
          
          # running jenkins-job-status.sh script
          "python3 ${GITHUB_WORKSPACE}/.github/scripts/jenkins-trigger-build.py http://20.106.205.93:8080/job/fake-server-pipeline/31/"
      
