# This is a basic workflow to help you get started with Actions

name: Trigger Jenkins Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  pull_request:
   branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
          
      - name: Install python dependencies
        run: pip install requests

      - name: Run python script to trigger build and fetch job number
        run: |
          # making file runnable (might be unnecessary)...
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/jenkins-trigger-build.py"
          
          # running jenkins-trigger-build.py script
          python3 "${GITHUB_WORKSPACE}/.github/scripts/jenkins-trigger-build.py" > "${GITHUB_WORKSPACE}/job_number.txt"
          
          cat "${GITHUB_WORKSPACE}/job_number.txt"
      
